# Generated by Django 3.1.14 on 2023-02-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shp',
            old_name='file',
            new_name='shp_file',
        ),
    ]
