# Generated by Django 3.1.14 on 2024-06-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0004_auto_20240628_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shp',
            name='unzip_folder_path',
        ),
        migrations.AddField(
            model_name='shp',
            name='shp_file_folder_path',
            field=models.CharField(blank=True, default='undefined', max_length=1000),
        ),
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='shp/20240628164301'),
        ),
    ]
