# Generated by Django 3.1.14 on 2024-06-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0006_auto_20240628_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='shp_default'),
        ),
    ]
