# Generated by Django 3.1.14 on 2024-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0007_auto_20240628_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file_folder_path',
            field=models.CharField(blank=True, default='shp_default', max_length=1000),
        ),
    ]
