# Generated by Django 3.1.14 on 2024-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0020_auto_20240628_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='shp/20240628_231939'),
        ),
    ]
