# Generated by Django 3.1.14 on 2024-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0023_auto_20240629_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='shp/20240629_131224'),
        ),
    ]
