# Generated by Django 3.1.14 on 2024-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0024_auto_20240629_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='shp/20240629_133850'),
        ),
    ]
