# Generated by Django 3.1.14 on 2024-07-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0030_auto_20240630_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='shp/%Y%m%d_%H%M%S'),
        ),
    ]
