# Generated by Django 3.1.14 on 2024-07-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiff',
            name='tiff_file_folder_path',
            field=models.CharField(blank=True, default='undefined', max_length=1000),
        ),
    ]
