# Generated by Django 3.1.14 on 2024-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_auto_20230219_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='shp',
            name='unzip_folder_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='uploaded_files/shp'),
        ),
    ]
