# Generated by Django 3.1.14 on 2024-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0003_auto_20240628_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='shp/20240628162125'),
        ),
        migrations.AlterField(
            model_name='shp',
            name='unzip_folder_path',
            field=models.CharField(blank=True, default='shp/20240628162125', max_length=1000),
        ),
    ]
