# Generated by Django 3.1.14 on 2024-06-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0008_auto_20240628_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file_folder_path',
            field=models.CharField(blank=True, default='undefined', max_length=1000),
        ),
    ]
