# Generated by Django 3.1.14 on 2024-06-29 14:50

from django.db import migrations, models
import shp.configs


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0027_auto_20240629_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to=shp.configs.generate_uploaded_shp_file_relpath),
        ),
    ]
