# Generated by Django 3.1.14 on 2024-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0029_auto_20240629_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='shp_file',
            field=models.FileField(upload_to='shp/20240630_085645'),
        ),
    ]
